apiVersion: v1
kind: Service
metadata:
  name: headlesschrome
  namespace: headless
spec:
  type: NodePort
  ports:
  - protocol: TCP
    name: headlesschrome
    port: 3000
    targetport: 3000
    nodeport: 32011

  selector:
    app: headlesschrome

